# Generated by Django 4.0.4 on 2022-05-08 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
